const app = document.getElementById('app');
let token = localStorage.getItem('token') || '';
const esc = (s='') => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');

async function api(path,opt={}){opt.headers=Object.assign({},opt.headers||{}, {'Authorization':'Bearer '+token,'content-type':'application/json'});const r=await fetch(path,opt);let d={};try{d=await r.json()}catch(_){d={}}return [r,d];}

function login(){app.innerHTML=`<div class="card"><h2>Login</h2><input id=u value=admin><input id=p type=password value=Admin123><button id=l>Login</button><pre id=m></pre></div>`;document.getElementById('l').onclick=async()=>{const username=document.getElementById('u').value;const password=document.getElementById('p').value;const [r,d]=await api('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password})});if(!r.ok){document.getElementById('m').textContent=d.detail||'error';return;}token=d.token;localStorage.setItem('token',token);main();};}

async function main(){const [rd,dash]=await api('/api/dashboard');if(rd.status===401){login();return;}const [,conf]=await api('/api/config');const [,cluster]=await api('/api/cluster/settings');app.innerHTML=`<div class="card"><button id=lo>Logout</button></div><div class="grid"><div class="card"><h3>24h</h3>${dash.processed_24h||0}</div><div class="card"><h3>1h</h3>${dash.processed_1h||0}</div><div class="card"><h3>Rejected16h</h3>${dash.rejected_16h||0}</div><div class="card"><h3>Active</h3>${esc(dash.active_node||'')}</div></div>
<div class="card"><h3>Cluster/Node/TLS/SSH</h3><div class=row><input id=node_id value="${esc(cluster.node_id||'')}"><input id=node_ip value="${esc(cluster.node_ip||'')}"></div><div class=row><input id=peer_node_ip value="${esc(cluster.peer_node_ip||'')}"><input id=vip_address value="${esc(cluster.vip_address||'')}"></div><div class=row><input id=vrrp_priority value="${cluster.vrrp_priority||100}"><select id=cluster_mode><option ${cluster.cluster_mode==='standalone'?'selected':''}>standalone</option><option ${cluster.cluster_mode==='master'?'selected':''}>master</option><option ${cluster.cluster_mode==='slave'?'selected':''}>slave</option></select></div><input id=master_api_url value="${esc(cluster.master_api_url||'')}" placeholder="master api url"><input id=master_api_token value="${esc(cluster.master_api_token||'')}" placeholder="master api token"><input id=peer_ssh_user value="${esc(cluster.peer_ssh_user||'root')}" placeholder="peer ssh user"><textarea id=tls_crt placeholder='tls cert'></textarea><textarea id=tls_key placeholder='tls key'></textarea><textarea id=ssh_private_key placeholder='ssh private key'></textarea><textarea id=ssh_known_hosts placeholder='known hosts'></textarea><button id=save_cluster>Save Cluster Settings</button></div>
<div class="grid"><div class="card"><h3>Allowed Domains</h3><input id=domain placeholder='example.com'><button id=add_domain>Add</button><ul>${(conf.domains||[]).map(d=>`<li>${esc(d.domain)}</li>`).join('')}</ul></div><div class="card"><h3>Routes</h3><input id=sd placeholder='sender-domain'><input id=th placeholder='target host'><input id=tp value='25'><button id=add_route>Add Route</button><ul>${(conf.routes||[]).map(r=>`<li>@${esc(r.sender_domain)} -> ${esc(r.target_host)}:${r.target_port}</li>`).join('')}</ul></div></div><div class="card"><button id=test>Konfiguration testen</button><button id=apply>Änderungen übernehmen</button><pre id=out></pre></div>`;
 document.getElementById('lo').onclick=()=>{localStorage.removeItem('token');token='';login();};
 document.getElementById('save_cluster').onclick=async()=>{const body={node_id:node_id.value,node_ip:node_ip.value,peer_node_ip:peer_node_ip.value,vip_address:vip_address.value,vrrp_priority:parseInt(vrrp_priority.value,10),cluster_mode:cluster_mode.value,master_api_url:master_api_url.value||null,master_api_token:master_api_token.value||null,peer_ssh_user:peer_ssh_user.value||'root',tls_crt:tls_crt.value||null,tls_key:tls_key.value||null,ssh_private_key:ssh_private_key.value||null,ssh_known_hosts:ssh_known_hosts.value||null};const [,d]=await api('/api/cluster/settings',{method:'POST',body:JSON.stringify(body)});out.textContent=JSON.stringify(d,null,2)};
 document.getElementById('add_domain').onclick=async()=>{await api('/api/domains',{method:'POST',body:JSON.stringify({domain:domain.value})});main();};
 document.getElementById('add_route').onclick=async()=>{await api('/api/routes',{method:'POST',body:JSON.stringify({sender_domain:sd.value,target_host:th.value,target_port:parseInt(tp.value,10),tls_mode:'opportunistic',tls_verify:false})});main();};
 document.getElementById('test').onclick=async()=>{const [,d]=await api('/api/config/test',{method:'POST',body:'{}'});out.textContent=JSON.stringify(d,null,2)};
 document.getElementById('apply').onclick=async()=>{const [,d]=await api('/api/config/apply',{method:'POST',body:'{}'});out.textContent=JSON.stringify(d,null,2)};
}

token?main():login();
